export const trendingResponse = {
    "sections": [
        {
            "title": "English Trending",
            "id": "discover_playlist",
            "options": [
                "English",
                "Global",
                "Arabic",
                "Bengali",
                "Chinese",
                "Czech",
                "Dutch",
                "Finnish",
                "French",
                "German",
                "Greek",
                "Gujarati",
                "Hebrew",
                "Hindi",
                "Hungarian",
                "Indonesian",
                "Italian",
                "Japanese",
                "Kazakh",
                "Korean",
                "Malay",
                "Persian",
                "Polish",
                "Portuguese",
                "Panjabi",
                "Russian",
                "Spanish",
                "Swedish",
                "Tagalog",
                "Tamil",
                "Telugu",
                "Thai",
                "Turkish",
                "Ukrainian",
                "Urdu",
                "Vietnamese"
            ],
            "selected_option": "English",
            "secondary_options": [
                "Now",
                "Weekly",
                "Monthly",
                "All Time"
            ],
            "secondary_selected_option": "Now",
            "section_name": "trending_songs",
            "style_type": "normal",
            "section_type": "playlist",
            "items": [
                {
                    "id": "a63cc9ec-7238-45d7-a227-b1d99d7254bc",
                    "entity_type": "song_schema",
                    "video_url": "https://cdn1.suno.ai/a63cc9ec-7238-45d7-a227-b1d99d7254bc.mp4",
                    "audio_url": "https://cdn1.suno.ai/a63cc9ec-7238-45d7-a227-b1d99d7254bc.mp3",
                    "image_url": "https://cdn2.suno.ai/a63cc9ec-7238-45d7-a227-b1d99d7254bc_da65ddbc.jpeg",
                    "image_large_url": "https://cdn2.suno.ai/a63cc9ec-7238-45d7-a227-b1d99d7254bc_da65ddbc.jpeg",
                    "major_model_version": "v4.5",
                    "model_name": "chirp-auk",
                    "metadata": {
                        "tags": "synthwave, lo-fi, indie rock, disco dance, phonk beat",
                        "prompt": "[Intro]\nOh, I’m tracing stars with a broken map — still lost, je me perds, je me perds\nAh, I’m calling out but your heart’s off-track — pas de lumière, pas de repère\n\n[Verse 1]\nCaught in a maze of my mind, I can’t tell where I began\nDes ombres sur les murs, des pas inconnus — où suis-je vraiment ?\nI picture your face in the firelight, but I’m scared to touch the flame\nOne step forward, two back in time, je danse encore avec ton nom\n\n[Pre-Chorus]\nBut I still believe you’re out there somewhere\nDonne-moi un signe, je viendrai vers toi\nYou bring the silence, I’ll bring the sky\nSous les étoiles gelées, je crie pour toi\n\n[Chorus]\nAh-woo, searching for you with a compass, mais tu t’effaces, tu te caches\nOh-oh, love in your heart like a fortress, je ne peux pas monter, je ne peux pas\nAh-woo, calling your name through the night wind, le vent me trahit encore\nHaha, of course I’d chase the impossible—c’est ma folie, c’est mon sort\n\n[Verse 2]\nLeave me alone if you need to, I still hold the dream inside\nTu me manques comme l’aube, quand les larmes commencent à tomber\nIt hurts ‘cause it’s all too familiar—my clock says there’s half an hour\nDis-moi, où es-tu maintenant ? Et qui suis-je sans ta lumière ?\n\n[Pre-Chorus]\nStill got the fire, still got the map\nTrace-moi une route, je n’abandonnerai pas\nYou bring the distance, I’ll bring the run\nÀ travers les mondes, je cours vers toi\n\n[Chorus]\nAh-woo, searching for you with a compass, mais tu t’éloignes, tu disparais\nOh-oh, love in your heart like a fortress, je frappe, mais rien ne s’ouvre jamais\nAh-woo, calling your name through the night wind, mais ton écho s’efface\nHaha, of course I’d chase the impossible — j’y vais, quoi qu’il se passe\n\n[Bridge]\nAh, ah, ah, ah — tu m’entends, là-haut ?\nOh, oh, oh, oh — je parle aux nuages\nWe were planets misaligned, now I float, I fly\nJe poursuis ton ombre dans le ciel froid\n\n[Final Chorus]\nAh-woo, still searching for you with a compass, mais je ne te trouve jamais\nOh-oh, love in your heart still haunts me — ça brûle encore, je ne peux l’oublier\nAh-woo, I scream through the void with a last breath, peut-être tu m’entendras\nHaha... but if you don’t, je garde l’espoir, je te laisse là\n\n[Outro]\nOh, I’m tracing stars with a broken map — je suis perdu, mais j’essaie, j’essaie\nAh, maybe your love was a ghostlight... mais je me lève, je me lève, je me lève",
                        "type": "gen",
                        "duration": 254.88,
                        "can_remix": true,
                        "is_remix": false,
                        "refund_credits": false,
                        "stream": true,
                        "priority": 10
                    },
                    "caption": "halfway is enough",
                    "is_liked": false,
                    "user_id": "5f0a911a-8224-4637-a04e-d8efa15dfa2e",
                    "display_name": "ari",
                    "handle": "omniamore",
                    "is_handle_updated": true,
                    "avatar_image_url": "https://cdn1.suno.ai/e372ed14.webp",
                    "is_trashed": false,
                    "explicit": false,
                    "comment_count": 56,
                    "flag_count": 3,
                    "created_at": "2025-05-02T23:19:37.006Z",
                    "status": "complete",
                    "title": "broken compass",
                    "play_count": 13546,
                    "upvote_count": 565,
                    "is_public": true,
                    "allow_comments": true,
                    "display_tags": "synthwave, lo-fi, indie rock, disco dance, phonk beat"
                },
                {
                    "id": "34945fa9-adfb-4841-9c6f-68fbe1de0df8",
                    "entity_type": "song_schema",
                    "video_url": "https://cdn1.suno.ai/34945fa9-adfb-4841-9c6f-68fbe1de0df8.mp4",
                    "video_cover_url": "https://cdn1.suno.ai/video_upload_b1e29ed0-35fe-404e-9bf3-4f9ee3fb0098.mp4",
                    "preview_url": "https://cdn1.suno.ai/video_upload_b1e29ed0-35fe-404e-9bf3-4f9ee3fb0098_preview.mp4",
                    "audio_url": "https://cdn1.suno.ai/34945fa9-adfb-4841-9c6f-68fbe1de0df8.mp3",
                    "image_url": "https://cdn2.suno.ai/image_video_upload_b1e29ed0-35fe-404e-9bf3-4f9ee3fb0098_snapshot_0s.jpeg",
                    "image_large_url": "https://cdn2.suno.ai/image_large_video_upload_b1e29ed0-35fe-404e-9bf3-4f9ee3fb0098_snapshot_0s.jpeg",
                    "major_model_version": "v4.5",
                    "model_name": "chirp-auk",
                    "metadata": {
                        "tags": "r&b, hip-hop, female, male, duet, 88bpm, 808s, reverb vocals",
                        "prompt": "[Female - Intro]\nnah nah nah\nla la la\nnah nah nah\nla la la\n\n[Female - Verse ]\nI just packed my bag\nLeft you so slowly\nYou can keep all of your things\nAct like you know me\nHeard the words you said\nYou never showed me\nNow you tryna slide right back\nI’m done - don’t hold me\n\n[Female - Pre-Chorus]:\nI don’t wanna play you like the old me\u2028\nYou don’t hit my line sayin’ you wanna hold me\u2028\nNow you in your feels, yeah babe I know that\nTryna spin the block, no baby, I won’t go back\n\n[Female - Chorus]:\nYou told me\nYou know me\nThen showed me\nYou don’t own me\u2028\u2028\nYou told me\nYou know me\nThen showed me\nYou don’t own me\n\n[Male Rap Verse]:\nI ain’t say the right things when I had the time\nToo busy tryna win, caught up in my pride\nYou was movin’ different, I ain't even ask why\nNow I'm scrollin' through your page just to feel that high\n\nI ain’t think you’d leave, thought you'd ride or stay\nNow your bag packed up, you ain’t call all day\nYou got cold in the eyes, no words to say\nGuess the real ones leave when you move that way\n\n[Female & Male - Chorus]:\nYou told me\nYou know me\nThen showed me\nYou don’t own me\u2028\u2028\nYou told me\nYou know me\nThen showed me\nYou don’t own me\n\n[Outro]\n",
                        "type": "gen",
                        "duration": 132.36,
                        "video_upload_width": 720,
                        "video_upload_height": 720,
                        "can_remix": true,
                        "is_remix": true,
                        "has_vocal": false,
                        "refund_credits": false,
                        "stream": true,
                        "priority": 10,
                        "cover_clip_id": "19822f85-2c51-4a1c-9c3a-c9eae1747da5",
                        "task": "cover"
                    },
                    "caption": "New Music Friday 🔥",
                    "is_liked": false,
                    "user_id": "d6a774a3-adb3-4cd3-b315-754180ccafd4",
                    "display_name": "Yamill",
                    "handle": "yamill",
                    "is_handle_updated": true,
                    "avatar_image_url": "https://cdn1.suno.ai/af392a24.webp",
                    "is_trashed": false,
                    "explicit": false,
                    "comment_count": 33,
                    "flag_count": 11,
                    "created_at": "2025-05-02T19:15:23.275Z",
                    "status": "complete",
                    "title": "CRUSHED",
                    "play_count": 13027,
                    "upvote_count": 460,
                    "is_public": true,
                    "allow_comments": true,
                    "display_tags": "r&b, hip-hop"
                },
            ],
            "preview_items_count": 2
        }
    ],
    "page": 0,
    "total_sections": 1,
    "page_size": 2,
    "start_index": 0
}