export const trendingStatus = {
    "sections": [
        {
            "title": "",
            "id": "featured_feed",
            "section_type": "featured_feed",
            "items": [
                {
                    "id": "featured_feed_for_you",
                    "title": "For You",
                    "link": "/for-you",
                    "mobile_link": "",
                    "items": [],
                    "item_type": "song_schema"
                },
                {
                    "id": "featured_feed_following",
                    "title": "Suggested Creators",
                    "link": "/feed",
                    "mobile_link": "",
                    "items": [],
                    "item_type": "following_feed_item_schema"
                },
                {
                    "id": "featured_feed_trending",
                    "title": "Trending",
                    "link": "/trending",
                    "mobile_link": "",
                    "items": [
                        {
                            "id": "307bf850-6d49-44f6-858e-23e29a64d1b5",
                            "entity_type": "song_schema",
                            "video_url": "https://cdn1.suno.ai/307bf850-6d49-44f6-858e-23e29a64d1b5.mp4",
                            "audio_url": "https://cdn1.suno.ai/307bf850-6d49-44f6-858e-23e29a64d1b5.mp3",
                            "image_url": "https://cdn2.suno.ai/image_307bf850-6d49-44f6-858e-23e29a64d1b5.jpeg",
                            "image_large_url": "https://cdn2.suno.ai/image_large_307bf850-6d49-44f6-858e-23e29a64d1b5.jpeg",
                            "major_model_version": "v4.5",
                            "model_name": "chirp-auk",
                            "metadata": {
                                "tags": "Chicago rap, clear vocals, conscious drill, soul-trap, boom bap roots, pitched-down gospel samples, ambient vinyl crackle, reversed piano loops, 808 slides, spoken-word interludes, breath-heavy delivery, gritty realism, layered rhyme schemes, inner-city storytelling, chipmunk samples, samples",
                                "prompt": "[Intro]\nSometimes I wonder if the water remembers\nAll the faces it watched disappear...\n\n[Verse 1]\nMama lit candles by the kitchen light\nPrayin’ I’d come home and not another fight\nGunshots echo, that’s the lullaby\nSirens sing over babies cry\nI used to dream of a safer block\nWhere doors ain’t locked and the clocks don’t stop\nBut time froze when my brother went away\nNow his name's on the wall where the memories stay\n\nI talk to shadows that walk with me\nThey know the struggle, the hustle, the heat\nEvery move’s a gamble, every step a bet\nBut the dice roll heavy when you’re swimmin’ in debt\nI’m just tryna find peace, but it's hard to breathe\nIn a city where hope’s as rare as belief\nBut even in the dark, I still find the spark\nEven when I’m lost, I’m still playin’ my part\n\n[Pre-Chorus]\nI ain't tryna be a statistic\nI ain't tryna be just another name\nBut they teach you early in this game\nTo survive, you gotta learn how to fight through the pain\n\n[Chorus]\nAshes in the lake, washed away with the rain\nEverything we lose, everything we gain\nI walk through the fire, but I’m still intact\nEvery step I take, I’m pullin' myself back\nAshes in the lake, but I still see the light\nI’m chasin' tomorrow, but I’m fightin’ tonight\nEvery scar on my soul, every crack in the ground\nI’ll be here forever, won’t let it bring me down\n\n[Verse 2]\nYou can see it in the eyes, the pain’s deep-set\nBut you can’t hide from the struggle you ain’t met\nLost friends, lost time, but I keep pressin’\nEvery day’s a blessing, but it’s hard to learn the lesson\nI’m out here tryna chase what’s left of me\nCan’t let the ghosts bury me beneath the streets\nI put my trust in these beats and these bars\nI wear my heart on my sleeve, battle scars\n\n[Pre-Chorus]\nI ain't tryna be a statistic\nI ain't tryna be just another name\nBut they teach you early in this game\nTo survive, you gotta learn how to fight through the pain\n\n[Chorus]\nAshes in the lake, washed away with the rain\nEverything we lose, everything we gain\nI walk through the fire, but I’m still intact\nEvery step I take, I’m pullin' myself back\nAshes in the lake, but I still see the light\nI’m chasin' tomorrow, but I’m fightin’ tonight\nEvery scar on my soul, every crack in the ground\nI’ll be here forever, won’t let it bring me down\n\n[Bridge]\nThey say the city don’t forgive, but I’m not here for forgiveness.\nI’m here to learn, to grow, to make it out, even if it’s one step at a time.\n'Cause in the end, it’s not the streets that define me.\nIt’s the fight in my heart.\n\n[Chorus]\nAshes in the lake, washed away with the rain\nEverything we lose, everything we gain\nI walk through the fire, but I’m still intact\nEvery step I take, I’m pullin' myself back\nAshes in the lake, but I still see the light\nI’m chasin' tomorrow, but I’m fightin’ tonight\nEvery scar on my soul, every crack in the ground\nI’ll be here forever, won’t let it bring me down\n\n[Outro]\nAshes in the lake... but we still rise.\nKeep walkin’, keep fightin’, we still alive.",
                                "edited_clip_id": "d3006332-af57-4394-b034-6360b6886af6",
                                "type": "edit_fade",
                                "duration": 209.8,
                                "edit_session_id": "780b354a-dc81-4ca3-b706-6ea060ed9505",
                                "can_remix": true,
                                "is_remix": false
                            },
                            "is_liked": false,
                            "user_id": "f87d023d-e7cb-45a8-9343-8ed13c961bbf",
                            "display_name": "DreamOUT",
                            "handle": "dreamout",
                            "is_handle_updated": true,
                            "avatar_image_url": "https://cdn1.suno.ai/2f369987.webp",
                            "is_trashed": false,
                            "explicit": false,
                            "comment_count": 45,
                            "flag_count": 5,
                            "created_at": "2025-05-02T00:16:46.717Z",
                            "status": "complete",
                            "title": "Ashes In The Lake",
                            "play_count": 11582,
                            "upvote_count": 582,
                            "is_public": true,
                            "allow_comments": true
                        },
                        {
                            "id": "6a2d9bb4-9804-4638-9abc-be63af682add",
                            "entity_type": "song_schema",
                            "video_url": "https://cdn1.suno.ai/6a2d9bb4-9804-4638-9abc-be63af682add.mp4",
                            "audio_url": "https://cdn1.suno.ai/6a2d9bb4-9804-4638-9abc-be63af682add.mp3",
                            "image_url": "https://cdn2.suno.ai/6a2d9bb4-9804-4638-9abc-be63af682add_45c78345.jpeg",
                            "image_large_url": "https://cdn2.suno.ai/6a2d9bb4-9804-4638-9abc-be63af682add_45c78345.jpeg",
                            "major_model_version": "v4.5",
                            "model_name": "chirp-auk",
                            "metadata": {
                                "tags": "funk-rap bounce, alt hip hop, Neo-Soul-Infused Deep House, groovy, funk soul, spacing",
                                "prompt": "yeah i really only came to kick it\nsomething, like soccer, or judo \nmy mind gone, to new planet\nmaybe pluto, \nwho know? \nyou really wanna fight like it's sumo\nlet it go motherfucker, who do you know?\nweed will take you up to mars, baby i ain't talking bruno\ni might even play my cards, yeah reverse like it's uno\nlook you gonna be a star, okay fine here yo' kudos\nsorta like alaska, cold as ice, baby juno\nmeanwhile, ima take a break for a moment\ndeep breath in, baby pray for atonement\noh you show it? \nima find a place to hold emotion\nfore i phone in like a bomb threat, and blow it\nback to the hangin', games playin on the play station\nwaste time, blurry like my eyes need lasik\nbaseline bumping you can hear it in a space ship\nfeeling like i'm playin for the lakers, amazin\n\n[chorus]\nso \nwanna vibe baby bring a friend\ni extend my brother's hand \ni would rather stay in, rip the pen\nbefore you! turn! off! all the lights! \n\n[verse 2]\ncause we ain't got a \nlot of time left\ni manuver like the heimlich, very upset\ni been workin' like a migrant\nall the success, ain't improved upon where i been\nso ima do me and take another fuckin' night in\nreally? boy i see ya trippin psilocybin\nspouting off some shit like you done opened up the hydrant\nlovin' is the drug, but i don't know if you supplyin'\ni don't want for this to get violent\nbut i take your silence, as guilt, or serious complicity\ndont mistake my kindness, for any authenticity\ni'ma turn the dial up to burn, in the sixth degree\none day we gonna make history, finna see\n\n\n\n[chorus]\nwoah slow your roll\nbaby we ain't gonna do too much tonight\nso you can slide\nand come inside\nbut on your way please grab my food and flick the lights\n\ncause this ain't magic\nrather i'd say that it feels just quite alright\nour love ain't average\nyour touch will keep me up into the night\n\nwanna ride baby bring a friend, \ni extend my brothers hand\ni would rather stay in bed\nso please turn off the lights!",
                                "concat_history": [
                                    {
                                        "id": "b035b82f-cfda-47df-b1f9-18e73fdab453",
                                        "type": "concat",
                                        "infill": false,
                                        "source": "web",
                                        "continue_at": 125.08
                                    },
                                    {
                                        "id": "fda12b77-9e05-4c86-b56b-f636368d4d82"
                                    }
                                ],
                                "type": "concat",
                                "duration": 210.91997916666668,
                                "edit_session_id": "18692e05-95c0-42a5-88bd-0dddbb318f21",
                                "can_remix": true,
                                "is_remix": false
                            },
                            "caption": "get outta here",
                            "is_liked": false,
                            "user_id": "2aaf8adb-9953-496d-bea9-0b1d79f98fb0",
                            "display_name": "chunck 🐐",
                            "handle": "chunck",
                            "is_handle_updated": true,
                            "avatar_image_url": "https://cdn1.suno.ai/c866ee34.webp",
                            "is_trashed": false,
                            "explicit": false,
                            "comment_count": 49,
                            "flag_count": 10,
                            "created_at": "2025-05-01T22:58:34.595Z",
                            "status": "complete",
                            "title": "f*** you, let's hang",
                            "play_count": 21870,
                            "upvote_count": 612,
                            "is_public": true,
                            "allow_comments": true
                        },
                    ],
                    "item_type": "song_schema",
                    "feed_metadata": {
                        "feed_metadata_type": "trending_metadata",
                        "language": "",
                        "language_text": "Global",
                        "lang_map_keys": [
                            "Global",
                            "Arabic",
                            "Bengali",
                            "Chinese",
                            "Czech",
                            "Dutch",
                            "English",
                            "Finnish",
                            "French",
                            "German",
                            "Greek",
                            "Gujarati",
                            "Hebrew",
                            "Hindi",
                            "Hungarian",
                            "Indonesian",
                            "Italian",
                            "Japanese",
                            "Kazakh",
                            "Korean",
                            "Malay",
                            "Persian",
                            "Polish",
                            "Portuguese",
                            "Panjabi",
                            "Russian",
                            "Spanish",
                            "Swedish",
                            "Tagalog",
                            "Tamil",
                            "Telugu",
                            "Thai",
                            "Turkish",
                            "Ukrainian",
                            "Urdu",
                            "Vietnamese"
                        ],
                        "ranking_map_keys": [
                            "Now",
                            "Weekly",
                            "Monthly",
                            "All Time"
                        ],
                        "rank_text": "Now"
                    },
                    "feed_metadata_type": "trending_metadata"
                }
            ]
        },
        {
            "title": "Best of v4.5",
            "id": "480b0308-492b-4649-9a59-1d7c6782aa04",
            "link": "/playlist/480b0308-492b-4649-9a59-1d7c6782aa04",
            "section_name": "campaign_playlists",
            "style_type": "normal",
            "section_type": "playlist",
            "items": [
                {
                    "id": "962ecc39-8b37-4d98-9fa8-09a80433ddc4",
                    "entity_type": "song_schema",
                    "video_url": "https://cdn1.suno.ai/962ecc39-8b37-4d98-9fa8-09a80433ddc4.mp4",
                    "audio_url": "https://cdn1.suno.ai/962ecc39-8b37-4d98-9fa8-09a80433ddc4.mp3",
                    "image_url": "https://cdn2.suno.ai/962ecc39-8b37-4d98-9fa8-09a80433ddc4_4da22d16.jpeg",
                    "image_large_url": "https://cdn2.suno.ai/962ecc39-8b37-4d98-9fa8-09a80433ddc4_4da22d16.jpeg",
                    "major_model_version": "v4.5",
                    "model_name": "chirp-auk",
                    "metadata": {
                        "tags": "Male vocal,Moody glitch-pop, experimental alt-electronic, stuttered emotive vocals, dark ambient undertones, lo-fi drum kit, glitchy synth arpeggios, rhythmic layering, restrained emotional delivery.\n",
                        "prompt": "[Intro]  \n[Ambient synth pads, distant filtered vocals, no drums]  \nEverybody is talking  \nNobody is stopping  \nEveryone is sharing the dark part of their thoughts  \nBut turning away in the face of uncertainty,  \nNo sharing everything I've got, no  \n\n[Chorus]  \n[Lo-fi beat and bass drop in glitchy synth arpeggios, layered autotuned vocals]  \nDon't begin withou-ou-ou-ou-out me,  \nDon't begin withou-ou-ou-ou-out me.  \nEven when I fault you, I'm so screwed without you,  \nNo, no…  \n\n[Verse 1]  \n[Vocals filtered minimal percussion]  \nScarfing down the system  \nStarving out our existence  \nRepeating our little phrases  \nTo try and save our own skin  \nSo they don't abuse us again  \nThe mental game is their name  \nThe part that keeps us sane  \nIs us shouting out our own brains  \nSacrificed again  \nBelow us is our friends  \nHope you haven't forgot about me, no  \n\n[Chorus]  \n[Beat returns glitchy synths added harmonies on vocals]  \nDon't begin withou-ou-ou-ou-out me,  \nDon't begin withou-ou-ou-ou-out me.  \nEven when I fault you, I'm so screwed without you,  \nNo, no, no, no  \n\n[Verse 2]  \n[Beat stripped back atmospheric synth swells]  \nStarved by our own decisions  \nStarved by their insecurities  \nStarved by their authorities  \nStarved out by my own immaturity  \nThese tears might be the death of me  \nTears lead to the darkness inside of me  \nDon't know that part of me  \n\n[Chorus]  \n[Full arrangement emotive, restrained vocals]  \nDon't begin withou-ou-ou-ou-out me,  \nDon't begin withou-ou-ou-ou-out me.  \nEven when I fault you, I'm so screwed without you,  \nNo, no, no, no  \n\n[Bridge Outro Chant]  \n[Chant with reverb instruments fade out gradually]  \nHey hey hey hey  \nHey hey hey hey  \nHey hey hey hey",
                        "type": "gen",
                        "duration": 173.44,
                        "refund_credits": false,
                        "stream": true,
                        "can_remix": true,
                        "is_remix": false,
                        "priority": 10
                    },
                    "is_liked": false,
                    "user_id": "c01dfb59-98e5-4735-8f3c-0d6605804f68",
                    "display_name": "AroundOnce",
                    "handle": "aroundonce",
                    "is_handle_updated": true,
                    "avatar_image_url": "https://cdn1.suno.ai/cd2e690b.webp",
                    "is_trashed": false,
                    "explicit": false,
                    "comment_count": 41,
                    "flag_count": 3,
                    "display_tags": "glitch-pop, experimental alt-electronic, dark ambient",
                    "created_at": "2025-05-01T16:50:43.452Z",
                    "status": "complete",
                    "title": "Fault V4.5",
                    "play_count": 11810,
                    "upvote_count": 488,
                    "is_public": true,
                    "allow_comments": true
                },
                {
                    "id": "540b88c8-0373-45bf-bf33-4cecb7c6f800",
                    "entity_type": "song_schema",
                    "video_url": "https://cdn1.suno.ai/540b88c8-0373-45bf-bf33-4cecb7c6f800.mp4",
                    "video_cover_url": "https://cdn1.suno.ai/video_upload_1efcaec4-9a0d-4ede-9ff8-48dea6f2e64c.mp4",
                    "preview_url": "https://cdn1.suno.ai/video_upload_1efcaec4-9a0d-4ede-9ff8-48dea6f2e64c_preview.mp4",
                    "audio_url": "https://cdn1.suno.ai/540b88c8-0373-45bf-bf33-4cecb7c6f800.mp3",
                    "image_url": "https://cdn2.suno.ai/image_video_upload_1efcaec4-9a0d-4ede-9ff8-48dea6f2e64c_snapshot_0s.jpeg",
                    "image_large_url": "https://cdn2.suno.ai/image_large_video_upload_1efcaec4-9a0d-4ede-9ff8-48dea6f2e64c_snapshot_0s.jpeg",
                    "major_model_version": "v4.5",
                    "model_name": "chirp-auk",
                    "metadata": {
                        "tags": "Afroswing Experimental Teemuth",
                        "prompt": "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n// © 2025 Teemuth\n\n🎵 Suno: https://suno.com/@teemuth\n\n🎵 Spotify: open.spotify.com/artist/6OiYRjnt94boE4iFYvNZa5?si=n8GN72wDSkqZds7MJtY--w\n\n📺 YouTube: youtube.com/@Teemuth_\n\n🐦\u200d⬛ Twitter/X: x.com/real_teemuth\n\n🎮 hyperfollow.com/realteemuth\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n[Verse]\nSaid I’m a survivor (yeah!)\nSee how I’m smilin’ (uh)\nTook all the pressure\nStill I’m risin’ (woo!)\nOoh—\n\nBeen through the struggle (struggle)\nFelt the whole quake (quake)\nDidn’t lose shine—\nNah, I don’t break (don’t break!)\nStill survivin’ (still here!)\nOoh—\n\n[Pre-Chorus]\nSo let’s light up the rhythm (light it!)\nWatch how I glide (watch me!)\nFeel this momentum—\nI’m touchin’ the sky (uh-huh!)\nOh—\n\n[Chorus]\nSurvivor! (Say it loud!)\nSurvivor! (Beat that drum!)\nOoh—\nSurvivor! (Call me that!)\nSurvivor! (Can’t hold back!)\nOoh— (Ooh—)\n\n[Verse]\nTried to break my spirit (they tried!)\nThey thought they could kill it (they lied!)\nBut I bounce back—\nWith more rhythm in it! (let’s ride!)\nNo—\nThey can’t touch this (nah!)\nMm—\n\nAnd I know you feel me (you do!)\nLook how far we’ve run (so far!)\nClimbin’ through storms\nNow we movin’ as one\nYeah—\nNow we havin’ fun (say it!)\nUh—\n\n[Chorus]\nSurvivor! (You know the name!)\nSurvivor! (No shame, no shame!)\nOoh—\nSurvivor! (Say it twice!)\nSurvivor! (That’s my life!)\nOoh— (Ooh!)\n\n[Final Chorus]\nSurvivor! (You know the name!)\nSurvivor! (No shame, no shame!)\nOoh—\nSurvivor! (Say it twice!)\nSurvivor! (That’s my life!)\nOoh— (Ooh!)\n\n",
                        "edited_clip_id": "e55988dc-c316-43e7-ba02-c8a038a1c103",
                        "type": "edit_crop",
                        "duration": 195.24,
                        "has_vocal": false,
                        "video_upload_width": 1440,
                        "video_upload_height": 1440,
                        "edit_session_id": "a8d4e5be-4dac-4710-b3b1-6f420b2f20c4",
                        "can_remix": false,
                        "is_remix": false
                    },
                    "caption": "Let's Survive Together!",
                    "is_liked": false,
                    "user_id": "1ede38ea-6231-4886-ba66-0f25eb4edc40",
                    "display_name": "Teemuth",
                    "handle": "teemuth",
                    "is_handle_updated": true,
                    "avatar_image_url": "https://cdn1.suno.ai/9f56ae1f.webp",
                    "is_trashed": false,
                    "explicit": false,
                    "comment_count": 41,
                    "flag_count": 6,
                    "created_at": "2025-05-01T16:04:17.935Z",
                    "status": "complete",
                    "title": "Survivor",
                    "play_count": 15406,
                    "upvote_count": 421,
                    "is_public": true,
                    "allow_comments": true
                },
            ],
            "preview_items_count": 4
        },
        {
            "title": "Now in Motion",
            "id": "7679c335-16d4-419b-8254-5cd2c3f16b99",
            "link": "/playlist/7679c335-16d4-419b-8254-5cd2c3f16b99",
            "section_name": "campaign_playlists",
            "style_type": "normal",
            "section_type": "playlist",
            "items": [
                {
                    "id": "f04dc954-6900-42db-a096-d813ba523e6f",
                    "entity_type": "song_schema",
                    "video_url": "https://cdn1.suno.ai/f04dc954-6900-42db-a096-d813ba523e6f.mp4",
                    "video_cover_url": "https://cdn1.suno.ai/video_upload_f44032e5-3634-4312-8f0c-610d42360988.mp4",
                    "preview_url": "https://cdn1.suno.ai/video_upload_f44032e5-3634-4312-8f0c-610d42360988_preview.mp4",
                    "audio_url": "https://cdn1.suno.ai/f04dc954-6900-42db-a096-d813ba523e6f.mp3",
                    "image_url": "https://cdn2.suno.ai/image_video_upload_f44032e5-3634-4312-8f0c-610d42360988_snapshot_0s.jpeg",
                    "image_large_url": "https://cdn2.suno.ai/image_large_video_upload_f44032e5-3634-4312-8f0c-610d42360988_snapshot_0s.jpeg",
                    "major_model_version": "v4",
                    "model_name": "chirp-v4",
                    "metadata": {
                        "tags": "reggaeton,  perreo",
                        "prompt": "Verso 1\nSalíamos sin plan, solas por ahí,\nCon mi amiga, siempre sabes cómo es.\nNada de preocupaciones, solo pasarla bien,\nUnas risas, una cerveza, y todo es cien.\nCoro\nTú y yo, sin pensar en nada,\nRiendo todo el día, sin drama.\nNo hace falta mucho para disfrutar,\nCon mi mejor amiga, no hay más que hablar.\nVerso 2\nCalle, música y un par de historias,\nHablando de todo, sin apuros ni glorias.\nLo bueno se da fácil cuando estamos juntas,\nAsí somos, sin estrés, sin vueltas.\nCoro\nTú y yo, sin pensar en nada,\nRiendo todo el día, sin drama.\nNo hace falta mucho para disfrutar,\nCon mi mejor amiga, no hay más que hablar.\nPuente\nY si el día se acaba, ya nos da igual,\nSeguimos en lo nuestro, siempre real.\nLo importante es estar, nada más,\nTodo fluye con ella, siempre al compás.\nCoro\nTú y yo, sin pensar en nada,\nRiendo todo el día, sin drama.\nNo hace falta mucho para disfrutar,\nCon mi mejor amiga, no hay más que hablar.\nCoro\nTú y yo, sin pensar en nada,\nRiendo todo el día, sin drama.\nNo hace falta mucho para disfrutar,\nCon mi mejor amiga, no hay más que hablar.\n",
                        "concat_history": [
                            {
                                "id": "164c55a3-8546-4de9-9a00-d7ce67050f68",
                                "type": "gen",
                                "infill": true,
                                "source": "web",
                                "infill_dur_s": 9.68,
                                "infill_end_s": 9.68,
                                "infill_lyrics": "Verso 1\nSalíamos sin plan, solas por ahí,\nCon mi amiga, siempre sabes cómo es.",
                                "infill_start_s": 0.0,
                                "include_future_s": 2.0,
                                "include_history_s": 2.0,
                                "infill_context_end_s": 39.68,
                                "infill_context_start_s": 0
                            },
                            {
                                "id": "5b05284f-87ce-4dde-8009-0f6332f1c368"
                            }
                        ],
                        "type": "concat_infilling",
                        "duration": 164.92,
                        "video_upload_width": 1080,
                        "video_upload_height": 1920,
                        "edit_session_id": "3ef674de-0318-4f71-b213-479f1c670950",
                        "can_remix": true,
                        "is_remix": false
                    },
                    "is_liked": false,
                    "user_id": "be7a2ab8-d60e-4a1e-866b-185a5777116e",
                    "display_name": "Clara",
                    "handle": "claraco",
                    "is_handle_updated": true,
                    "avatar_image_url": "https://cdn1.suno.ai/5d29d3bf.webp",
                    "is_trashed": false,
                    "explicit": false,
                    "comment_count": 250,
                    "flag_count": 43,
                    "created_at": "2025-03-26T02:13:05.554Z",
                    "status": "complete",
                    "title": "Siempre ready",
                    "play_count": 115321,
                    "upvote_count": 3293,
                    "is_public": true,
                    "allow_comments": true
                },
                {
                    "id": "074ae404-a8d5-4e35-a84a-0b6f22eee22e",
                    "entity_type": "song_schema",
                    "video_url": "https://cdn1.suno.ai/074ae404-a8d5-4e35-a84a-0b6f22eee22e.mp4",
                    "video_cover_url": "https://cdn1.suno.ai/video_upload_8615853c-05be-4279-ba57-6c037d0dba5a.mp4",
                    "preview_url": "https://cdn1.suno.ai/video_upload_8615853c-05be-4279-ba57-6c037d0dba5a_preview.mp4",
                    "audio_url": "https://cdn1.suno.ai/074ae404-a8d5-4e35-a84a-0b6f22eee22e.mp3",
                    "image_url": "https://cdn2.suno.ai/image_video_upload_8615853c-05be-4279-ba57-6c037d0dba5a_snapshot_0s.jpeg",
                    "image_large_url": "https://cdn2.suno.ai/image_large_video_upload_8615853c-05be-4279-ba57-6c037d0dba5a_snapshot_0s.jpeg",
                    "major_model_version": "v4",
                    "model_name": "chirp-v4",
                    "metadata": {
                        "tags": "quirky, unique voice, alternative r&b, art pop, progressive soul, introspective, progressive, psychedelic",
                        "prompt": "[Verse]\nI'm losin' myself\nI'm losin' my mind\nWhy did they leave me all out in the cold\nWith tears in my eyes\n\n[Verse]\nAnd I'm tryin' my best\nTo keep myself whole\nBut how can I give something to you\nThat is not in my own control\n\n[Chorus]\nI've loved people heartless\nAnd I've fallen the hardest\nI'm myself\nI promise\nBut sometimes I'm someone else\nI think I've lost my mind now\nI just hope I'll be fine now\nAnd it's nothing you've done wrong\nI'm sorry I'm not strong\nSomeone told me I'm all wrong\n\n[Bridge]\nThis is uncharted territory\nBut boy\nTell me different stories\nAnd you\nYou say that I deserve the world\nBut I've already got what I want\n\n[Verse]\n'Cause I'm losin' myself\nAnd I'm losin' my mind\nWhy did they leave me all out in the cold\nTo figure out why\n\n[Instrumental break]\n\n[Chorus]\nI've loved people heartless\nAnd I've fallen the hardest\nI'm myself\nI promise\nBut sometimes I'm someone else\nAnd I think I've lost my mind now\n'Cause when I learned the truth\nI cried out\nBut I'll figure it all out",
                        "edited_clip_id": "3b244243-558d-455b-b8a7-9889a05ca582",
                        "type": "edit_crop",
                        "duration": 210.6,
                        "video_upload_width": 1214,
                        "video_upload_height": 2160,
                        "edit_session_id": "e7289be7-d604-409a-ab08-10bb4929714a",
                        "can_remix": true,
                        "is_remix": false
                    },
                    "caption": "Cowritten with ReMi",
                    "is_liked": false,
                    "user_id": "0a22188e-a3a2-4a6c-a108-30c0cae4d752",
                    "display_name": "IO",
                    "handle": "ian",
                    "is_handle_updated": true,
                    "avatar_image_url": "https://cdn1.suno.ai/631e956e.webp",
                    "is_trashed": false,
                    "explicit": false,
                    "comment_count": 178,
                    "flag_count": 19,
                    "created_at": "2025-01-15T21:27:06.791Z",
                    "status": "complete",
                    "title": "Heartless",
                    "play_count": 115337,
                    "upvote_count": 2971,
                    "is_public": true,
                    "allow_comments": true
                },
            ],
            "preview_items_count": 4
        },
        {
            "title": "Featured",
            "id": "featured_playlists",
            "section_name": "tastemaker_playlists",
            "style_type": "featured",
            "section_type": "playlist_list",
            "items": [
                {
                    "id": "6e758550-bbaf-4dc9-b00c-a2a9af2b003a",
                    "entity_type": "playlist_schema",
                    "image_url": "https://cdn2.suno.ai/b68e1840.jpeg",
                    "playlist_clips": [],
                    "current_page": 0,
                    "num_total_results": 21,
                    "is_owned": false,
                    "is_trashed": false,
                    "is_public": false,
                    "user_display_name": "Ghostplayer",
                    "user_handle": "ghostplayermusic",
                    "user_avatar_image_url": "https://cdn1.suno.ai/34d24a8e.webp",
                    "upvote_count": 3,
                    "dislike_count": 0,
                    "flag_count": 0,
                    "skip_count": 0,
                    "play_count": 596,
                    "song_count": 21,
                    "name": "Unplug 🧘",
                    "description": "Deep breaths... relax your mind... perfect for deep focus, sleep, or mediation",
                    "is_discover_playlist": false
                },
                {
                    "id": "09367564-e5df-4a5e-b5c7-04cc057c0b77",
                    "entity_type": "playlist_schema",
                    "image_url": "https://cdn2.suno.ai/GENRE_COVER_IMG_ChillWave.jpeg",
                    "playlist_clips": [],
                    "current_page": 0,
                    "num_total_results": 62,
                    "is_owned": false,
                    "is_trashed": false,
                    "is_public": true,
                    "user_display_name": "GROOVEBOT",
                    "user_handle": "groovebot",
                    "user_avatar_image_url": "https://cdn1.suno.ai/defaultBlue.webp",
                    "upvote_count": 15,
                    "dislike_count": 1,
                    "flag_count": 0,
                    "skip_count": 0,
                    "play_count": 3670,
                    "song_count": 62,
                    "name": "Chillwave",
                    "description": "Sunsets and nostalgia for memories you never actually had",
                    "is_discover_playlist": true
                },
            ]
        },
        {
            "title": "New Songs",
            "id": "new_songs_playlist",
            "section_name": "new_songs_playlist",
            "style_type": "normal",
            "section_type": "playlist",
            "items": [
                {
                    "id": "b6569497-1b2c-4f1c-a861-8e46e30a8de9",
                    "entity_type": "song_schema",
                    "video_url": "https://cdn1.suno.ai/b6569497-1b2c-4f1c-a861-8e46e30a8de9.mp4",
                    "audio_url": "https://cdn1.suno.ai/b6569497-1b2c-4f1c-a861-8e46e30a8de9.mp3",
                    "image_url": "https://cdn2.suno.ai/image_b6569497-1b2c-4f1c-a861-8e46e30a8de9.jpeg",
                    "image_large_url": "https://cdn2.suno.ai/image_large_b6569497-1b2c-4f1c-a861-8e46e30a8de9.jpeg",
                    "major_model_version": "v4.5",
                    "model_name": "chirp-ahi-up-1",
                    "metadata": {
                        "tags": "bang it, hard core, rock, east coast rap, male vocals, hit it, let it rip, bad ass metal",
                        "prompt": "[Intro] \n\n[Guitar Interlude]\n\n[Verse]\nSaw her in the moonlight sneakin through the night\nEyes like glowing embers set the world alight\nHeart of mischief laughter’s on the rise\nDanger in her smile oh baby’s got snake eyes\n\n[Pre-Chorus]\nCharming eyes so bright\nHer love is a painful delight (oh yeah)\nYou won’t know until she bites\n\n[Chorus]\nEvery step she takes she’s light and free\nLurking in the shadows fate’s decree\nWhispers of her past they mesmerize\nCareful where you tread ‘cause baby’s got snake eyes\n\n[Break]\n[Instrumental Interlude]\n\n[Verse 2]\nWalking on a tightrope charm is her disguise\nTrading sweetened venom and the sweetest lies\nMystery woman’s got me so hypnotized\nFalling for her spell now baby’s got snake eyes\n\n[Pre-Chorus]\nCharming eyes so bright\nHer love is a painful delight (oh yeah)\nYou won’t know until she bites\n\n[Chorus]\nEvery step she takes she’s light and free\nLurking in the shadows fate’s decree\nWhispers of her past they mesmerize\nCareful where you tread ‘cause baby’s got snake eyes\n\n[Break]\n[Instrumental Interlude]\n\n[Bridge]\nShe’s a secret weapon under moonlit skies\nA riddle wrapped in starlight truth belies\nCaught in her enchantment took me by surprise\nI’m frozen in her stare ‘cause baby’s got snake eyes\n\n[Guitar Solo]\n\n[Verse 3]\nHer snaky curves coiled around me\nShe sinks her fangs into me\nNow stricken by her poison\nI am doomed to her dungeon ‘cause baby’s got snake eyes\n\n[Pre-Chorus]\nCharming eyes so bright\nHer love is a painful delight (oh yeah)\nYou won’t know until she bites\n\n[Chorus]\nEvery step she takes she’s light and free\nLurking in the shadows fate’s decree\nWhispers of her past they mesmerize\nCareful where you tread ‘cause baby’s got snake eyes\n\n[Instrumental Fadeout]\n\n[End]\n",
                        "edited_clip_id": "a8a1457f-fc01-4bea-a006-b410a550fffd",
                        "type": "upsample",
                        "duration": 239.0,
                        "refund_credits": false,
                        "stream": false,
                        "upsample_clip_id": "a8a1457f-fc01-4bea-a006-b410a550fffd",
                        "task": "upsample",
                        "can_remix": true,
                        "is_remix": false,
                        "priority": 10
                    },
                    "is_liked": false,
                    "user_id": "c43d02d2-3820-4ce6-9b24-2a44012ec6d5",
                    "display_name": "FreddyMax [YouTube @FreddyMaxOfficial]",
                    "handle": "freddymax",
                    "is_handle_updated": true,
                    "avatar_image_url": "https://cdn1.suno.ai/1d702fce.webp",
                    "is_trashed": false,
                    "explicit": false,
                    "comment_count": 0,
                    "flag_count": 0,
                    "created_at": "2025-05-03T10:00:41.397Z",
                    "status": "complete",
                    "title": "Baby's Got Snake Eyes Extended (Remastered)",
                    "play_count": 11,
                    "upvote_count": 7,
                    "is_public": true,
                    "allow_comments": true
                },
                {
                    "id": "c7db5a49-0da0-47fb-9ffc-072b930a665b",
                    "entity_type": "song_schema",
                    "video_url": "https://cdn1.suno.ai/c7db5a49-0da0-47fb-9ffc-072b930a665b.mp4",
                    "audio_url": "https://cdn1.suno.ai/c7db5a49-0da0-47fb-9ffc-072b930a665b.mp3",
                    "image_url": "https://cdn2.suno.ai/c7db5a49-0da0-47fb-9ffc-072b930a665b_c50c1f53.jpeg",
                    "image_large_url": "https://cdn2.suno.ai/c7db5a49-0da0-47fb-9ffc-072b930a665b_c50c1f53.jpeg",
                    "major_model_version": "v4.5",
                    "model_name": "chirp-auk",
                    "metadata": {
                        "tags": "Instrumental\n8D audio, lounge, ethereal jazz",
                        "prompt": "",
                        "type": "gen",
                        "duration": 140.72,
                        "refund_credits": false,
                        "stream": true,
                        "can_remix": true,
                        "is_remix": false,
                        "priority": 10
                    },
                    "is_liked": false,
                    "user_id": "5daefb1f-2673-4ce1-bb19-90ee744a79fe",
                    "display_name": "Larissa Kryukova (@lvk music)",
                    "handle": "adrenalinefueledplaylists6930",
                    "is_handle_updated": true,
                    "avatar_image_url": "https://cdn1.suno.ai/c5fe4c2e.webp",
                    "is_trashed": false,
                    "explicit": false,
                    "comment_count": 0,
                    "flag_count": 0,
                    "display_tags": "lounge, ethereal jazz, instrumental",
                    "created_at": "2025-05-03T09:37:51.001Z",
                    "status": "complete",
                    "title": "LVK Instrumental  - # 173",
                    "play_count": 62,
                    "upvote_count": 17,
                    "is_public": true,
                    "allow_comments": true
                },
            ],
            "preview_items_count": 2
        }
    ],
    "page": 0,
    "total_sections": 12,
    "page_size": 5,
    "start_index": 0
}